### ISSUE TITLE
Share a new release 

### ISSUE THREAD

**Issue by hosnifraj0** [MikeAndrson/Dexter#3]

**Comment by omeraydindev** [comment]
If you mean an APK, you can always find built debug APKs under **Android CI** in https://github.com/MikeAndrson/Dexter/actions. If there isn't any recent one you can always fork this repo and run the workflows yourself to build an APK.

With that being said; if you meant an actual Github Release, since this project is still very much in beta and is subject to drastic changes -- I don't want to publish any releases yet.

**Comment by hosnifraj0** [comment]
Ok thanks
